 server.port=${PORT:8080}
spring.application.name=servidorlocal

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.max-http-header-size=128k

spring.h2.console.enabled=false


# Configuracoes do servidor de Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ismaralfama222@gmail.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# JWT
jwt.secret=${JWT_SECRET:fsfgç.aofgvzçvhçhhççzasefhcaçshfcahçasfvahfahafclflcfdfilhabcdafhcaidfajskdhfiesfiu}